"use client";
import React, { useState, useEffect } from "react";
import axios from "axios";
import Papa from "papaparse";
import LeadList from "@/app/components/leadmanagement/leadlist";
import LeadForm from "@/app/components/leadmanagement/leadform";
import { Box } from "@mui/material";
import LoadingComponent from "@/app/components/generalComponent/loadingcomponent";

interface Lead {
  _id: string;
  userId: string;
  fields: Array<{ id: string; label: string; value: string | string[] | any }>;
  createdAt: string;
  status: "new" | "available" | "sold" | "assigned";
  distributionMethod: "manual" | "round_robin" | "marketplace";
  exclusive: boolean;
  shared: boolean;
  shareNumber: number;
  unit: number;
  isManual: boolean;
}

const LeadManagement: React.FC = () => {
  const [leads, setLeads] = useState<Lead[]>([]);
  const [openDialog, setOpenDialog] = useState(false);
  const [selectedLead, setSelectedLead] = useState<Lead | null>(null);
  const [fieldLabels, setFieldLabels] = useState<string[]>([]);
  const [loading, setLoading] = useState(true);

  const extractLeads = (data: any): Lead[] => {
    if (Array.isArray(data)) return data as Lead[];
    if (Array.isArray(data?.leads)) return data.leads as Lead[];
    if (Array.isArray(data?.data?.leads)) return data.data.leads as Lead[];
    return [];
  };

  // Fetch leads and initialize field labels
  useEffect(() => {
    const fetchLeads = async () => {
      try {
        const response = await axios.get("/api/leads");

        const leadsData = extractLeads(response.data);
        setLeads(leadsData);

        // Extract unique field labels
        const labelsSet = new Set<string>();
        if (Array.isArray(leadsData)) {
          leadsData.forEach((lead) => {
            if (lead.fields && Array.isArray(lead.fields)) {
              lead.fields.forEach((field) => labelsSet.add(field.label));
            }
          });
        }
        setFieldLabels(Array.from(labelsSet));
      } catch (error) {
        console.error("Error fetching leads", error);
      } finally {
        setLoading(false);
      }
    };

    fetchLeads();
  }, []);

  // Open the dialog for adding or editing a lead
  const handleOpenDialog = (lead: Lead | null = null) => {
    if (lead) {
      // Editing an existing lead: use the lead's _id and userId
      setSelectedLead(lead);
    } else {
      // Adding a new lead: use the userId from the first lead in the list (or fetch it dynamically)
      const defaultUserId =
        leads.length > 0 ? leads[0].userId : "defaultUserId";
      setSelectedLead({
        _id: "", // _id will be generated by MongoDB for new leads
        userId: defaultUserId,
        fields: [],
        createdAt: new Date().toISOString(),
        status: "new",
        distributionMethod: "marketplace",
        exclusive: false,
        unit: 5,
        shared: false,
        shareNumber: 0,
        isManual: true,
      });
    }
    setOpenDialog(true);
  };

  // Close the dialog
  const handleCloseDialog = () => {
    setOpenDialog(false);
    setSelectedLead(null);
  };

  // Handle form submission (create or update lead)
  const handleFormSubmit = async () => {
    if (selectedLead) {
      try {
        if (selectedLead._id) {
          // Update existing lead
          await axios.put(`/api/leads?id=${selectedLead._id}`, selectedLead);
        } else {
          // Create new lead (exclude _id)
          const { _id, ...newLead } = selectedLead;
          await axios.post(`/api/leads`, newLead);
        }

        // Refresh the leads list
        const response = await axios.get("/api/leads");
        setLeads(extractLeads(response.data));
        handleCloseDialog();
      } catch (error) {
        console.error("Error saving lead", error);
      }
    }
  };

  // Delete a lead
  const handleDeleteLead = async (leadId: string) => {
    try {
      await axios.delete(`/api/leads?id=${leadId}`);
      setLeads(leads.filter((lead) => lead._id !== leadId));
    } catch (error) {
      console.error("Error deleting lead", error);
    }
  };

  // Toggle favorite status
  const toggleFavorite = async (leadId: string) => {
    try {
      setLeads((prevLeads) =>
        prevLeads.map((lead) =>
          lead._id === leadId ? { ...lead, exclusive: !lead.exclusive } : lead,
        ),
      );

      await axios.patch(`/api/exclusive?id=${leadId}`, {
        exclusive: !leads.find((lead) => lead._id === leadId)?.exclusive,
      });
    } catch (error) {
      console.error("Error updating exclusive status", error);
    }
  };

  // Export leads to CSV
  const exportToCSV = () => {
    const csvData = leads.map((lead) => {
      const row: any = {
        "Created At": new Date(lead.createdAt).toLocaleString(),
        Status: lead.status,
        "Is Favorite": lead.exclusive ? "Yes" : "No",
        "Is Manual": lead.isManual ? "Yes" : "No",
      };
      lead.fields.forEach((field) => {
        row[field.label] = field.value;
      });

      return row;
    });

    const csv = Papa.unparse(csvData);
    const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.setAttribute("download", "leads.csv");
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  // Import leads from CSV
  const importFromCSV = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    try {
      const formData = new FormData();
      formData.append("file", file);

      const response = await axios.post("/api/leads/import", formData, {
        headers: {
          "Content-Type": "multipart/form-data",
        },
      });

      if (response.data.success) {
        // Refresh the leads list
        const leadsResponse = await axios.get("/api/leads");
        setLeads(extractLeads(leadsResponse.data));

        // Show success message
        alert(response.data.message);
      } else {
        console.error("Import failed:", response.data.message);
        alert("Import failed: " + response.data.message);
      }
    } catch (error) {
      console.error("Error importing leads", error);
      alert("Error importing leads. Please check the console for details.");
    } finally {
      // Reset the file input
      event.target.value = "";
    }
  };

  return (
    <Box
      sx={{
        width: "100%",
        maxWidth: "100%",
        overflowX: "hidden",
      }}
    >
      {loading ? (
        <Box
          sx={{
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
            height: "50vh",
          }}
        >
          <LoadingComponent />
        </Box>
      ) : (
        <LeadList
          leads={leads}
          onDeleteLead={handleDeleteLead}
          onToggleFavorite={toggleFavorite}
          handleOpenDialog={handleOpenDialog}
          onEditLead={handleOpenDialog}
          onExportCSV={exportToCSV}
          onImportCSV={importFromCSV}
          fieldLabels={fieldLabels}
        />
      )}
      <LeadForm
        open={openDialog}
        onClose={handleCloseDialog}
        onSubmit={handleFormSubmit}
        selectedLead={selectedLead}
        setSelectedLead={(lead) =>
          setSelectedLead((prev) =>
            typeof lead === "function" ? lead(prev as Lead) : lead,
          )
        }
      />
    </Box>
  );
};

export default LeadManagement;
