import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/authprovider";
import { NavigationProvider } from "../context/handlenavigation";
import { ThemeProvider } from "@/context/themeprovider";
import NotificationManager from "@/app/components/NotificationManager";
import MuiThemeProvider from "@/lib/theme/MuiThemeProvider";
import { Providers } from "@/app/reduxprovider";
import { CSRFProvider } from "@/app/hooks/useCSRF";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <MuiThemeProvider>
          <ThemeProvider>
            <AuthProvider>
              <NavigationProvider>
                <Providers>
                  <CSRFProvider>
                    {children}
                    <NotificationManager />
                  </CSRFProvider>
                </Providers>
              </NavigationProvider>
            </AuthProvider>
          </ThemeProvider>
        </MuiThemeProvider>
      </body>
    </html>
  );
}
