// Array of cities for the location dropdown
export const usCities = [
  // US Cities
  "New York, NY",
  "Los Angeles, CA",
  "Chicago, IL",
  "Houston, TX",
  "Phoenix, AZ",
  "Philadelphia, PA",
  "San Antonio, TX",
  "San Diego, CA",
  "Dallas, TX",
  "San Jose, CA",
  "Austin, TX",
  "Jacksonville, FL",
  "San Francisco, CA",
  "Indianapolis, IN",
  "Columbus, OH",
  "Fort Worth, TX",
  "Charlotte, NC",
  "Seattle, WA",
  "Denver, CO",
  "Washington, DC",
  "Boston, MA",
  "El Paso, TX",
  "Nashville, TN",
  "Detroit, MI",
  "Oklahoma City, OK",
  "Portland, OR",
  "Las Vegas, NV",
  "Memphis, TN",
  "Louisville, KY",
  "Baltimore, MD",
  "Milwaukee, WI",
  "Albuquerque, NM",
  "Tucson, AZ",
  "Fresno, CA",
  "Sacramento, CA",
  "Kansas City, MO",
  "Atlanta, GA",
  "Miami, FL",
  "Oakland, CA",
  "Minneapolis, MN",
  "Tulsa, OK",
  "Wichita, KS",
  "New Orleans, LA",
  "Arlington, TX",
  "Cleveland, OH",
  "Bakersfield, CA",
  "Tampa, FL",
  "Aurora, CO",
  "Honolulu, HI",
  "Anaheim, CA",
  "Santa Ana, CA",
  "Riverside, CA",
  "Corpus Christi, TX",
  "Lexington, KY",
  "Stockton, CA",
  "Henderson, NV",
  "Saint Paul, MN",
  "St. Louis, MO",
  "Cincinnati, OH",
  "Pittsburgh, PA",
  "Greensboro, NC",
  "Anchorage, AK",
  "Plano, TX",
  "Lincoln, NE",
  "Orlando, FL",
  "Irvine, CA",
  "Newark, NJ",
  "Toledo, OH",
  "Durham, NC",
  "Chula Vista, CA",
  "Fort Wayne, IN",
  "Jersey City, NJ",
  "St. Petersburg, FL",
  "Laredo, TX",
  "Madison, WI",
  "Chandler, AZ",
  "Buffalo, NY",
  "Lubbock, TX",
  "Scottsdale, AZ",
  "Reno, NV",
  "Glendale, AZ",
  "Gilbert, AZ",
  "Winston-Salem, NC",
  "North Las Vegas, NV",
  "Norfolk, VA",
  "Chesapeake, VA",
  "Garland, TX",
  "Irving, TX",
  "Hialeah, FL",
  "Fremont, CA",
  "Boise, ID",
  "Richmond, VA",
  "Baton Rouge, LA",
  "Spokane, WA",

  // UK Cities
  "London, England",
  "Birmingham, England",
  "Manchester, England",
  "Glasgow, Scotland",
  "Liverpool, England",
  "Leeds, England",
  "Newcastle upon Tyne, England",
  "Bristol, England",
  "Sheffield, England",
  "Edinburgh, Scotland",
  "Cardiff, Wales",
  "Belfast, Northern Ireland",
  "Leicester, England",
  "Coventry, England",
  "Nottingham, England",
  "Southampton, England",
  "Derby, England",
  "Portsmouth, England",
  "Brighton, England",
  "Plymouth, England",
  "Wolverhampton, England",
  "Swansea, Wales",
  "Milton Keynes, England",
  "Aberdeen, Scotland",
  "Reading, England",
  "Northampton, England",
  "Luton, England",
  "Swindon, England",
  "Warrington, England",
  "York, England",
  "Peterborough, England",
  "Dundee, Scotland",
  "Norwich, England",
  "Cambridge, England",
  "Oxford, England",
  "Exeter, England",
  "Ipswich, England",
  "Blackpool, England",
  "Middlesbrough, England",
  "Bournemouth, England",
  "Huddersfield, England",
  "Telford, England",
  "Preston, England",
  "Sunderland, England",
  "Gloucester, England",
  "Slough, England",
  "Poole, England",
  "Rotherham, England",
  "Newport, Wales",
  "Chester, England",
  "Chelmsford, England",

  // Canada Cities
  "Toronto, ON",
  "Montreal, QC",
  "Vancouver, BC",
  "Calgary, AB",
  "Edmonton, AB",
  "Ottawa, ON",
  "Winnipeg, MB",
  "Quebec City, QC",
  "Hamilton, ON",
  "Halifax, NS",
  "London, ON",
  "Victoria, BC",
  "Windsor, ON",
  "Oshawa, ON",
  "Saskatoon, SK",
  "Regina, SK",
  "St. John's, NL",
  "Barrie, ON",
  "Kelowna, BC",
  "Abbotsford, BC",
  "Kingston, ON",
  "Sherbrooke, QC",
  "Guelph, ON",
  "Trois-Rivieres, QC",
  "Whitehorse, YT",
  "Yellowknife, NT",
  "Iqaluit, NU",
  "Mississauga, ON",
  "Brampton, ON",
  "Surrey, BC",
  "Laval, QC",
  "Burnaby, BC",
  "Richmond, BC",
  "Richmond Hill, ON",
  "Oakville, ON",
  "Burlington, ON",
  "Vaughan, ON",
  "Markham, ON",
  "Kitchener, ON",
  "Ajax, ON",
  "Pickering, ON",
  "Thunder Bay, ON",
  "Gatineau, QC",
  "Waterloo, ON",
  "Cambridge, ON",
  "Coquitlam, BC",
  "Delta, BC",
  "Chatham, ON",
  "Red Deer, AB",
  "Lethbridge, AB",

  // Australia Cities
  "Sydney, NSW",
  "Melbourne, VIC",
  "Brisbane, QLD",
  "Perth, WA",
  "Adelaide, SA",
  "Gold Coast, QLD",
  "Newcastle, NSW",
  "Canberra, ACT",
  "Sunshine Coast, QLD",
  "Wollongong, NSW",
  "Geelong, VIC",
  "Hobart, TAS",
  "Townsville, QLD",
  "Cairns, QLD",
  "Darwin, NT",
  "Toowoomba, QLD",
  "Ballarat, VIC",
  "Bendigo, VIC",
  "Launceston, TAS",
  "Mackay, QLD",
  "Rockhampton, QLD",
  "Bunbury, WA",
  "Coffs Harbour, NSW",
  "Bundaberg, QLD",
  "Wagga Wagga, NSW",
  "Hervey Bay, QLD",
  "Albury, NSW",
  "Nowra, NSW",
  "Shepparton, VIC",
  "Gladstone, QLD",
  "Mildura, VIC",
  "Port Macquarie, NSW",
  "Orange, NSW",
  "Dubbo, NSW",
  "Geraldton, WA",
  "Bathurst, NSW",
  "Warrnambool, VIC",
  "Albany, WA",
  "Devonport, TAS",
  "Mount Gambier, SA",
  "Kalgoorlie, WA",
  "Lismore, NSW",
  "Maryborough, QLD",
  "Burnie, TAS",
  "Armidale, NSW",
  "Whyalla, SA",
  "Mount Isa, QLD",
  "Broken Hill, NSW",
  "Karratha, WA",
  "Alice Springs, NT",
];
