// Array of US cities for the location dropdown
export const usCities = [
  "New York, NY",
  "Los Angeles, CA",
  "Chicago, IL",
  "Houston, TX",
  "Phoenix, AZ",
  "Philadelphia, PA",
  "San Antonio, TX",
  "San Diego, CA",
  "Dallas, TX",
  "San Jose, CA",
  "Austin, TX",
  "Jacksonville, FL",
  "San Francisco, CA",
  "Indianapolis, IN",
  "Columbus, OH",
  "Fort Worth, TX",
  "Charlotte, NC",
  "Seattle, WA",
  "Denver, CO",
  "Washington, DC",
  "Boston, MA",
  "El Paso, TX",
  "Nashville, TN",
  "Detroit, MI",
  "Oklahoma City, OK",
  "Portland, OR",
  "Las Vegas, NV",
  "Memphis, TN",
  "Louisville, KY",
  "Baltimore, MD",
  "Milwaukee, WI",
  "Albuquerque, NM",
  "Tucson, AZ",
  "Fresno, CA",
  "Sacramento, CA",
  "Kansas City, MO",
  "Atlanta, GA",
  "Miami, FL",
  "Oakland, CA",
  "Minneapolis, MN",
  "Tulsa, OK",
  "Wichita, KS",
  "New Orleans, LA",
  "Arlington, TX",
  "Cleveland, OH",
  "Bakersfield, CA",
  "Tampa, FL",
  "Aurora, CO",
  "Honolulu, HI",
  "Anaheim, CA",
  "Santa Ana, CA",
  "Riverside, CA",
  "Corpus Christi, TX",
  "Lexington, KY",
  "Stockton, CA",
  "Henderson, NV",
  "Saint Paul, MN",
  "St. Louis, MO",
  "Cincinnati, OH",
  "Pittsburgh, PA",
  "Greensboro, NC",
  "Anchorage, AK",
  "Plano, TX",
  "Lincoln, NE",
  "Orlando, FL",
  "Irvine, CA",
  "Newark, NJ",
  "Toledo, OH",
  "Durham, NC",
  "Chula Vista, CA",
  "Fort Wayne, IN",
  "Jersey City, NJ",
  "St. Petersburg, FL",
  "Laredo, TX",
  "Madison, WI",
  "Chandler, AZ",
  "Buffalo, NY",
  "Lubbock, TX",
  "Scottsdale, AZ",
  "Reno, NV",
  "Glendale, AZ",
  "Gilbert, AZ",
  "Winston-Salem, NC",
  "North Las Vegas, NV",
  "Norfolk, VA",
  "Chesapeake, VA",
  "Garland, TX",
  "Irving, TX",
  "Hialeah, FL",
  "Fremont, CA",
  "Boise, ID",
  "Richmond, VA",
  "Baton Rouge, LA",
  "Spokane, WA",
];
