// utils/industryNiches.ts
"use client";

export const industryNiches = [
  { value: "real-estate", label: "Real Estate" },
  { value: "auto", label: "Automobile" },
  { value: "finance", label: "Finance" },
  { value: "health", label: "Health" },
  { value: "education", label: "Education" },
  { value: "technology", label: "Technology" },
  { value: "legal", label: "Legal" },
  { value: "construction", label: "Construction" },
  { value: "insurance", label: "Insurance" },
  { value: "marketing", label: "Marketing" },
  { value: "hospitality", label: "Hospitality" },
  { value: "ecommerce", label: "E-Commerce" },
  { value: "retail", label: "Retail" },
  { value: "travel", label: "Travel & Tourism" },
  { value: "logistics", label: "Logistics & Transportation" },
  { value: "home-services", label: "Home Services" },
  { value: "events", label: "Event Planning" },
  { value: "fitness", label: "Fitness & Wellness" },
  { value: "beauty", label: "Beauty & Personal Care" },
  { value: "media", label: "Media & Entertainment" },
  { value: "manufacturing", label: "Manufacturing" },
  { value: "agriculture", label: "Agriculture" },
  { value: "nonprofit", label: "Non-Profit" },
  { value: "security", label: "Security Services" },
  { value: "energy", label: "Energy & Utilities" },
  { value: "sports", label: "Sports & Recreation" },
  { value: "telecom", label: "Telecommunications" },
  { value: "plumbing", label: "Plumbing Services" },
  { value: "electrician", label: "Electrical Services" },
  { value: "hvac", label: "HVAC Services" },
  { value: "landscaping", label: "Landscaping & Gardening" },
  { value: "cleaning", label: "Cleaning Services" },
  { value: "pest-control", label: "Pest Control" },
  { value: "roofing", label: "Roofing Services" },
  { value: "painting", label: "Painting & Decorating" },
  { value: "handyman", label: "Handyman Services" },
  { value: "locksmith", label: "Locksmith Services" },
  { value: "moving", label: "Moving & Relocation" },
  { value: "tutoring", label: "Tutoring & Coaching" },
  { value: "pet-services", label: "Pet Care & Services" },
  { value: "childcare", label: "Childcare & Babysitting" },
  { value: "senior-care", label: "Senior Care Services" },
  { value: "catering", label: "Catering & Food Services" },
  { value: "photography", label: "Photography & Videography" },
  { value: "tattoo", label: "Tattoo & Piercing Services" },
  { value: "autorepair", label: "Auto Repair & Maintenance" },
  { value: "wedding-services", label: "Wedding Planning & Services" },
  { value: "accounting", label: "Accounting & Bookkeeping" },
  { value: "legal-services", label: "Legal & Paralegal Services" },
  { value: "consulting", label: "Consulting & Advisory" },
  { value: "it-services", label: "IT & Software Services" },
  { value: "human-resources", label: "Human Resources & Recruitment" },
  { value: "public-relations", label: "Public Relations & Communications" },
  { value: "translation", label: "Translation & Language Services" },
  { value: "therapy", label: "Therapy & Counseling" },
  { value: "research", label: "Research & Development" },
  { value: "graphic-design", label: "Graphic Design & Branding" },
  { value: "interior-design", label: "Interior Design & Home Staging" },
  { value: "data-science", label: "Data Science & Analytics" },
  { value: "event-security", label: "Event Security & Management" },
  { value: "music", label: "Music & Performing Arts" },
  { value: "gaming", label: "Gaming & Esports" },
  { value: "cybersecurity", label: "Cybersecurity & IT Security" },
  { value: "driving-school", label: "Driving Schools & Training" },
];
