// utils/industryServices.ts
"use client";

export const industryServices: Record<string, string[]> = {
  "real-estate": [
    "Residential Sales",
    "Commercial Sales",
    "Property Management",
    "Real Estate Consulting",
    "Home Inspection",
    "Mortgage Services",
    "Title Services",
    "Property Appraisal",
  ],
  auto: [
    "Vehicle Sales",
    "Auto Financing",
    "Vehicle Leasing",
    "Trade-in Appraisal",
    "Extended Warranty",
    "Vehicle Registration",
  ],
  finance: [
    "Personal Loans",
    "Business Loans",
    "Investment Advisory",
    "Wealth Management",
    "Credit Services",
    "Financial Planning",
  ],
  health: [
    "General Practitioner",
    "Specialist Consultation",
    "Dental Services",
    "Eye Care",
    "Mental Health",
    "Physical Therapy",
    "Pharmacy",
    "Medical Testing",
  ],
  education: [
    "Online Courses",
    "School Enrollment",
    "Tutoring Services",
    "Test Preparation",
    "Corporate Training",
    "Certification Programs",
  ],
  technology: [
    "Software Development",
    "IT Consulting",
    "Cloud Services",
    "Cybersecurity",
    "Web Development",
    "Mobile Development",
    "IT Support",
  ],
  legal: [
    "Contract Review",
    "Corporate Law",
    "Family Law",
    "Personal Injury",
    "Criminal Defense",
    "Estate Planning",
    "Immigration Law",
  ],
  construction: [
    "General Contracting",
    "Excavation",
    "Foundation Work",
    "Framing",
    "Project Management",
    "Design Services",
    "Inspection Services",
  ],
  insurance: [
    "Auto Insurance",
    "Home Insurance",
    "Life Insurance",
    "Business Insurance",
    "Health Insurance",
    "Travel Insurance",
  ],
  marketing: [
    "Digital Marketing",
    "SEO Services",
    "Social Media Marketing",
    "Content Creation",
    "Email Marketing",
    "Branding",
    "Market Research",
  ],
  hospitality: [
    "Hotel Booking",
    "Restaurant Reservations",
    "Event Hosting",
    "Catering",
    "Venue Rental",
  ],
  ecommerce: [
    "Online Store Setup",
    "Product Sourcing",
    "Inventory Management",
    "Payment Processing",
    "Shipping Services",
    "Customer Support",
  ],
  retail: [
    "Retail Sales",
    "Store Management",
    "Inventory Services",
    "Point of Sale",
    "Loss Prevention",
  ],
  travel: [
    "Flight Booking",
    "Hotel Booking",
    "Tour Packages",
    "Visa Services",
    "Travel Insurance",
    "Car Rental",
  ],
  logistics: [
    "Freight Services",
    "Package Delivery",
    "Warehouse Management",
    "Supply Chain",
    "Tracking Services",
  ],
  "home-services": [
    "Plumbing",
    "Electrical",
    "HVAC",
    "Carpentry",
    "Roofing",
    "Painting",
    "Landscaping",
    "Cleaning",
  ],
  events: [
    "Event Planning",
    "Venue Coordination",
    "Catering",
    "Photography",
    "Entertainment",
    "Decorations",
  ],
  fitness: [
    "Gym Membership",
    "Personal Training",
    "Yoga Classes",
    "Nutrition Coaching",
    "Wellness Programs",
  ],
  beauty: [
    "Hair Salon",
    "Massage Therapy",
    "Skincare",
    "Cosmetic Services",
    "Nail Services",
    "Esthetics",
  ],
  media: [
    "Video Production",
    "Photography",
    "Graphic Design",
    "Audio Production",
    "Content Creation",
  ],
  manufacturing: [
    "Product Design",
    "Production Planning",
    "Quality Control",
    "Equipment Maintenance",
    "Supply Management",
  ],
  agriculture: [
    "Farm Equipment",
    "Crop Consultation",
    "Soil Analysis",
    "Irrigation Services",
    "Pest Management",
  ],
  nonprofit: [
    "Fundraising",
    "Grant Writing",
    "Donor Management",
    "Program Planning",
    "Board Services",
  ],
  security: [
    "Personal Security",
    "Property Security",
    "Surveillance",
    "Security Consulting",
    "Bodyguard Services",
  ],
  energy: [
    "Solar Installation",
    "Energy Audit",
    "Utility Services",
    "Renewable Energy",
    "Energy Consulting",
  ],
  sports: [
    "Sports Coaching",
    "Fitness Training",
    "Equipment Sales",
    "Event Organization",
    "Sports Nutrition",
  ],
  telecom: [
    "Phone Services",
    "Internet Services",
    "Mobile Plans",
    "Data Services",
    "Tech Support",
  ],
  plumbing: [
    "Pipe Installation",
    "Leak Repair",
    "Drain Cleaning",
    "Water Heater",
    "Emergency Services",
  ],
  electrician: [
    "Electrical Installation",
    "Wiring",
    "Outlet Replacement",
    "Lighting",
    "Emergency Repairs",
  ],
  hvac: [
    "AC Installation",
    "Heating System",
    "Maintenance Plans",
    "Duct Cleaning",
    "Emergency Service",
  ],
  landscaping: [
    "Lawn Maintenance",
    "Tree Service",
    "Garden Design",
    "Hardscaping",
    "Seasonal Service",
  ],
  cleaning: [
    "House Cleaning",
    "Office Cleaning",
    "Window Cleaning",
    "Carpet Cleaning",
    "Deep Cleaning",
  ],
  "pest-control": [
    "Termite Treatment",
    "Pest Inspection",
    "Wildlife Removal",
    "Mosquito Control",
    "Bed Bug Treatment",
  ],
  roofing: [
    "Roof Installation",
    "Roof Repair",
    "Gutter Service",
    "Inspection",
    "Maintenance",
  ],
  painting: [
    "Interior Painting",
    "Exterior Painting",
    "Color Consultation",
    "Power Washing",
    "Staining",
  ],
  handyman: [
    "General Repairs",
    "Assembly",
    "Installation",
    "Maintenance",
    "Small Projects",
  ],
  locksmith: [
    "Lockout Service",
    "Lock Installation",
    "Key Duplication",
    "Security Systems",
    "Master Key",
  ],
  moving: [
    "Local Moving",
    "Long Distance",
    "Storage Services",
    "Packing Services",
    "Heavy Item Moving",
  ],
  tutoring: [
    "Academic Tutoring",
    "Test Prep",
    "Language Learning",
    "Music Lessons",
    "Professional Development",
  ],
  "pet-services": [
    "Dog Grooming",
    "Pet Sitting",
    "Veterinary",
    "Pet Training",
    "Pet Boarding",
  ],
  childcare: ["Babysitting", "Daycare", "Nanny Services", "After School Care"],
  "senior-care": [
    "In-Home Care",
    "Assisted Living",
    "Companion Care",
    "Medication Management",
    "Mobility Assistance",
  ],
  catering: [
    "Corporate Catering",
    "Wedding Catering",
    "Event Catering",
    "Menu Planning",
    "Delivery Service",
  ],
  photography: [
    "Portrait Photography",
    "Wedding Photography",
    "Event Photography",
    "Product Photography",
    "Video Services",
  ],
  tattoo: [
    "Tattoo Design",
    "Piercing Service",
    "Removal Service",
    "Consultation",
  ],
  autorepair: [
    "Engine Repair",
    "Transmission",
    "Brake Service",
    "Oil Change",
    "Tire Service",
  ],
  "wedding-services": [
    "Wedding Planning",
    "Venue Coordination",
    "Catering",
    "Photography",
    "Florals",
    "Entertainment",
  ],
  accounting: [
    "Bookkeeping",
    "Tax Preparation",
    "Payroll Services",
    "Financial Audit",
    "Tax Planning",
  ],
  "legal-services": [
    "Contract Review",
    "Legal Consultation",
    "Document Preparation",
    "Court Representation",
  ],
  consulting: [
    "Business Consulting",
    "Strategy Planning",
    "Process Improvement",
    "Change Management",
    "Interim Management",
  ],
  "it-services": [
    "IT Support",
    "Network Management",
    "System Administration",
    "Data Backup",
    "Security Services",
  ],
  "human-resources": [
    "Recruitment",
    "Employee Training",
    "HR Consulting",
    "Payroll Processing",
    "Compliance Services",
  ],
  "public-relations": [
    "Media Relations",
    "Press Release",
    "Crisis Management",
    "Social Media",
    "Brand Management",
  ],
  translation: [
    "Document Translation",
    "Interpretation",
    "Localization",
    "Transcription",
  ],
  therapy: [
    "Counseling",
    "Psychotherapy",
    "Coaching",
    "Stress Management",
    "Support Groups",
  ],
  research: [
    "Market Research",
    "Product Development",
    "Data Analysis",
    "Scientific Research",
  ],
  "graphic-design": [
    "Logo Design",
    "Web Design",
    "Branding",
    "Print Design",
    "UI/UX Design",
  ],
  "interior-design": [
    "Space Planning",
    "Furniture Selection",
    "Color Consultation",
    "Home Staging",
    "Renovation Design",
  ],
  "data-science": [
    "Data Analysis",
    "Machine Learning",
    "Business Intelligence",
    "Data Visualization",
    "Predictive Analytics",
  ],
  "event-security": [
    "Security Personnel",
    "Crowd Control",
    "Surveillance",
    "Risk Assessment",
    "Emergency Planning",
  ],
  music: [
    "Music Lessons",
    "Performance",
    "Recording",
    "Music Production",
    "DJ Services",
  ],
  gaming: [
    "Game Development",
    "Esports Coaching",
    "Tournament Organization",
    "Streaming Support",
    "Game Testing",
  ],
  cybersecurity: [
    "Security Audit",
    "Vulnerability Assessment",
    "Incident Response",
    "Security Training",
    "Penetration Testing",
  ],
  "driving-school": [
    "Driving Lessons",
    "Defensive Driving",
    "Vehicle Inspection",
    "License Preparation",
    "Professional Training",
  ],
};
