export const timezones = [
  { value: "Pacific/Midway", label: "Samoa Standard Time (SST)" },
  { value: "Pacific/Honolulu", label: "Hawaii Standard Time (HST)" },
  { value: "America/Anchorage", label: "Alaska Standard Time (AKST)" },
  { value: "America/Los_Angeles", label: "Pacific Time (PT)" },
  { value: "America/Denver", label: "Mountain Time (MT)" },
  { value: "America/Chicago", label: "Central Time (CT)" },
  { value: "America/New_York", label: "Eastern Time (ET)" },
  { value: "America/Caracas", label: "Venezuela Time (VET)" },
  { value: "America/Santiago", label: "Chile Standard Time (CLT)" },
  { value: "America/Sao_Paulo", label: "Brasília Time (BRT)" },
  { value: "Atlantic/South_Georgia", label: "South Georgia Time (GST)" },
  { value: "Atlantic/Azores", label: "Azores Standard Time (AZOT)" },
  { value: "Europe/London", label: "Greenwich Mean Time (GMT/BST)" },
  { value: "Europe/Paris", label: "Central European Time (CET)" },
  { value: "Europe/Athens", label: "Eastern European Time (EET)" },
  { value: "Africa/Lagos", label: "West Africa Time (WAT)" },
  { value: "Africa/Johannesburg", label: "South Africa Standard Time (SAST)" },
  { value: "Europe/Moscow", label: "Moscow Standard Time (MSK)" },
  { value: "Asia/Dubai", label: "Gulf Standard Time (GST)" },
  { value: "Asia/Karachi", label: "Pakistan Standard Time (PKT)" },
  { value: "Asia/Kolkata", label: "India Standard Time (IST)" },
  { value: "Asia/Dhaka", label: "Bangladesh Standard Time (BST)" },
  { value: "Asia/Bangkok", label: "Indochina Time (ICT)" },
  { value: "Asia/Shanghai", label: "China Standard Time (CST)" },
  { value: "Asia/Tokyo", label: "Japan Standard Time (JST)" },
  { value: "Asia/Seoul", label: "Korea Standard Time (KST)" },
  {
    value: "Australia/Perth",
    label: "Australian Western Standard Time (AWST)",
  },
  {
    value: "Australia/Adelaide",
    label: "Australian Central Standard Time (ACST)",
  },
  {
    value: "Australia/Sydney",
    label: "Australian Eastern Standard Time (AEST)",
  },
  { value: "Pacific/Auckland", label: "New Zealand Standard Time (NZST)" },
];
